################# 当前应用tomcat容器运行配置 ##############
server:
  port: 18081

################# 应用程序环境配置 ###############
spring:
  application:
    name: crystal-cluster-server
  redis:
    host: 111.230.152.81
    port: 16379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.230.152.81:3316/qianduan?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: qianduan
    password: QianDuan!123
    druid:
      initial-size: 2
      min-idle: 5
      max-active: 400
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,slf4j
      stat-view-servlet:
        login-username: druid
        login-password: druid
  messages:
    basename: i18n/message
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  resources:
    chain:
      cache: true
      enabled: true
      strategy:
        content:
          enabled: true
          paths: ["/css/**","/image/**","/js/**","/js-busi/**","/widget/tinymce/**"]
mybatis:
  mapper-locations: classpath*:/sqlmapper/**/*.xml
  type-aliases-package: com.ai.mine.*.dao.model;com.ai.mine.crystal.dao.model
logging:
  level:
    root: info
    org.springframework: warn

################# mine应用框架自定义配置数据示例 #################
application:
  configcenter:
    zkaddress: 127.0.0.1:2181
    runmode: D
    login: admin:admin
  security:
    admin-password: "admin"
    login-path: "admin/login/login"
    enabled-kaptcha: false
    web-permitall-url:
      - "/portal/**"
