package com.ai.mine.crystal.dao.model;

import java.util.Date;

public class TKedaVideoStorage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_video_storage.video_storage_id
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    private Long videoStorageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_video_storage.storage_path
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    private String storagePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_video_storage.storage_filename
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    private String storageFilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_video_storage.video_url
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    private String videoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_video_storage.record_id
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    private String recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_video_storage.case_id
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    private String caseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_video_storage.case_name
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    private String caseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_video_storage.asker
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    private String asker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_video_storage.persion_id
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    private String persionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_video_storage.create_time
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_video_storage.video_storage_id
     *
     * @return the value of t_keda_video_storage.video_storage_id
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public Long getVideoStorageId() {
        return videoStorageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_video_storage.video_storage_id
     *
     * @param videoStorageId the value for t_keda_video_storage.video_storage_id
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public void setVideoStorageId(Long videoStorageId) {
        this.videoStorageId = videoStorageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_video_storage.storage_path
     *
     * @return the value of t_keda_video_storage.storage_path
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public String getStoragePath() {
        return storagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_video_storage.storage_path
     *
     * @param storagePath the value for t_keda_video_storage.storage_path
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public void setStoragePath(String storagePath) {
        this.storagePath = storagePath == null ? null : storagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_video_storage.storage_filename
     *
     * @return the value of t_keda_video_storage.storage_filename
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public String getStorageFilename() {
        return storageFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_video_storage.storage_filename
     *
     * @param storageFilename the value for t_keda_video_storage.storage_filename
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public void setStorageFilename(String storageFilename) {
        this.storageFilename = storageFilename == null ? null : storageFilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_video_storage.video_url
     *
     * @return the value of t_keda_video_storage.video_url
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_video_storage.video_url
     *
     * @param videoUrl the value for t_keda_video_storage.video_url
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_video_storage.record_id
     *
     * @return the value of t_keda_video_storage.record_id
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_video_storage.record_id
     *
     * @param recordId the value for t_keda_video_storage.record_id
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_video_storage.case_id
     *
     * @return the value of t_keda_video_storage.case_id
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_video_storage.case_id
     *
     * @param caseId the value for t_keda_video_storage.case_id
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId == null ? null : caseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_video_storage.case_name
     *
     * @return the value of t_keda_video_storage.case_name
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public String getCaseName() {
        return caseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_video_storage.case_name
     *
     * @param caseName the value for t_keda_video_storage.case_name
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public void setCaseName(String caseName) {
        this.caseName = caseName == null ? null : caseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_video_storage.asker
     *
     * @return the value of t_keda_video_storage.asker
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public String getAsker() {
        return asker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_video_storage.asker
     *
     * @param asker the value for t_keda_video_storage.asker
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public void setAsker(String asker) {
        this.asker = asker == null ? null : asker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_video_storage.persion_id
     *
     * @return the value of t_keda_video_storage.persion_id
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public String getPersionId() {
        return persionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_video_storage.persion_id
     *
     * @param persionId the value for t_keda_video_storage.persion_id
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public void setPersionId(String persionId) {
        this.persionId = persionId == null ? null : persionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_video_storage.create_time
     *
     * @return the value of t_keda_video_storage.create_time
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_video_storage.create_time
     *
     * @param createTime the value for t_keda_video_storage.create_time
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}