package com.ai.mine.crystal.dao.model;

import java.util.Date;

public class TKedaRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_record.record_id
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    private String recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_record.record_uuid
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    private String recordUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_record.case_id
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    private String caseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_record.template_id
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    private String templateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_record.asker
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    private String asker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_record.persion_id
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    private String persionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_record.start_time
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_record.end_time
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_record.record_status
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    private String recordStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_record.record_type
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    private String recordType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_record.apply_id
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    private String applyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_record.remote_room
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    private String remoteRoom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_record.local_room
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    private String localRoom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_record.video_url
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    private String videoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_record.job_status
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    private String jobStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_record.job_time
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    private Date jobTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_record.record_id
     *
     * @return the value of t_keda_record.record_id
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_record.record_id
     *
     * @param recordId the value for t_keda_record.record_id
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_record.record_uuid
     *
     * @return the value of t_keda_record.record_uuid
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public String getRecordUuid() {
        return recordUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_record.record_uuid
     *
     * @param recordUuid the value for t_keda_record.record_uuid
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public void setRecordUuid(String recordUuid) {
        this.recordUuid = recordUuid == null ? null : recordUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_record.case_id
     *
     * @return the value of t_keda_record.case_id
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_record.case_id
     *
     * @param caseId the value for t_keda_record.case_id
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId == null ? null : caseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_record.template_id
     *
     * @return the value of t_keda_record.template_id
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_record.template_id
     *
     * @param templateId the value for t_keda_record.template_id
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId == null ? null : templateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_record.asker
     *
     * @return the value of t_keda_record.asker
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public String getAsker() {
        return asker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_record.asker
     *
     * @param asker the value for t_keda_record.asker
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public void setAsker(String asker) {
        this.asker = asker == null ? null : asker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_record.persion_id
     *
     * @return the value of t_keda_record.persion_id
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public String getPersionId() {
        return persionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_record.persion_id
     *
     * @param persionId the value for t_keda_record.persion_id
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public void setPersionId(String persionId) {
        this.persionId = persionId == null ? null : persionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_record.start_time
     *
     * @return the value of t_keda_record.start_time
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_record.start_time
     *
     * @param startTime the value for t_keda_record.start_time
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_record.end_time
     *
     * @return the value of t_keda_record.end_time
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_record.end_time
     *
     * @param endTime the value for t_keda_record.end_time
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_record.record_status
     *
     * @return the value of t_keda_record.record_status
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public String getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_record.record_status
     *
     * @param recordStatus the value for t_keda_record.record_status
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus == null ? null : recordStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_record.record_type
     *
     * @return the value of t_keda_record.record_type
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public String getRecordType() {
        return recordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_record.record_type
     *
     * @param recordType the value for t_keda_record.record_type
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public void setRecordType(String recordType) {
        this.recordType = recordType == null ? null : recordType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_record.apply_id
     *
     * @return the value of t_keda_record.apply_id
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public String getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_record.apply_id
     *
     * @param applyId the value for t_keda_record.apply_id
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public void setApplyId(String applyId) {
        this.applyId = applyId == null ? null : applyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_record.remote_room
     *
     * @return the value of t_keda_record.remote_room
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public String getRemoteRoom() {
        return remoteRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_record.remote_room
     *
     * @param remoteRoom the value for t_keda_record.remote_room
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public void setRemoteRoom(String remoteRoom) {
        this.remoteRoom = remoteRoom == null ? null : remoteRoom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_record.local_room
     *
     * @return the value of t_keda_record.local_room
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public String getLocalRoom() {
        return localRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_record.local_room
     *
     * @param localRoom the value for t_keda_record.local_room
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public void setLocalRoom(String localRoom) {
        this.localRoom = localRoom == null ? null : localRoom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_record.video_url
     *
     * @return the value of t_keda_record.video_url
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_record.video_url
     *
     * @param videoUrl the value for t_keda_record.video_url
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_record.job_status
     *
     * @return the value of t_keda_record.job_status
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public String getJobStatus() {
        return jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_record.job_status
     *
     * @param jobStatus the value for t_keda_record.job_status
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public void setJobStatus(String jobStatus) {
        this.jobStatus = jobStatus == null ? null : jobStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_record.job_time
     *
     * @return the value of t_keda_record.job_time
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public Date getJobTime() {
        return jobTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_record.job_time
     *
     * @param jobTime the value for t_keda_record.job_time
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    public void setJobTime(Date jobTime) {
        this.jobTime = jobTime;
    }
}