package com.ai.mine.crystal.dao.model;

import java.util.Date;

public class TKedaCaseinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_caseinfo.case_id
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    private String caseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_caseinfo.case_name
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    private String caseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_caseinfo.case_uuid
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    private String caseUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_caseinfo.case_number
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    private String caseNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_caseinfo.create_time
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_caseinfo.modify_time
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_caseinfo.area_id
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    private String areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_caseinfo.area_name
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    private String areaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_caseinfo.case_status
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    private String caseStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_caseinfo.job_status
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    private String jobStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_keda_caseinfo.job_time
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    private Date jobTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_caseinfo.case_id
     *
     * @return the value of t_keda_caseinfo.case_id
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_caseinfo.case_id
     *
     * @param caseId the value for t_keda_caseinfo.case_id
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId == null ? null : caseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_caseinfo.case_name
     *
     * @return the value of t_keda_caseinfo.case_name
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public String getCaseName() {
        return caseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_caseinfo.case_name
     *
     * @param caseName the value for t_keda_caseinfo.case_name
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public void setCaseName(String caseName) {
        this.caseName = caseName == null ? null : caseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_caseinfo.case_uuid
     *
     * @return the value of t_keda_caseinfo.case_uuid
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public String getCaseUuid() {
        return caseUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_caseinfo.case_uuid
     *
     * @param caseUuid the value for t_keda_caseinfo.case_uuid
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public void setCaseUuid(String caseUuid) {
        this.caseUuid = caseUuid == null ? null : caseUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_caseinfo.case_number
     *
     * @return the value of t_keda_caseinfo.case_number
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public String getCaseNumber() {
        return caseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_caseinfo.case_number
     *
     * @param caseNumber the value for t_keda_caseinfo.case_number
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public void setCaseNumber(String caseNumber) {
        this.caseNumber = caseNumber == null ? null : caseNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_caseinfo.create_time
     *
     * @return the value of t_keda_caseinfo.create_time
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_caseinfo.create_time
     *
     * @param createTime the value for t_keda_caseinfo.create_time
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_caseinfo.modify_time
     *
     * @return the value of t_keda_caseinfo.modify_time
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_caseinfo.modify_time
     *
     * @param modifyTime the value for t_keda_caseinfo.modify_time
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_caseinfo.area_id
     *
     * @return the value of t_keda_caseinfo.area_id
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_caseinfo.area_id
     *
     * @param areaId the value for t_keda_caseinfo.area_id
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_caseinfo.area_name
     *
     * @return the value of t_keda_caseinfo.area_name
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_caseinfo.area_name
     *
     * @param areaName the value for t_keda_caseinfo.area_name
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_caseinfo.case_status
     *
     * @return the value of t_keda_caseinfo.case_status
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public String getCaseStatus() {
        return caseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_caseinfo.case_status
     *
     * @param caseStatus the value for t_keda_caseinfo.case_status
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public void setCaseStatus(String caseStatus) {
        this.caseStatus = caseStatus == null ? null : caseStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_caseinfo.job_status
     *
     * @return the value of t_keda_caseinfo.job_status
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public String getJobStatus() {
        return jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_caseinfo.job_status
     *
     * @param jobStatus the value for t_keda_caseinfo.job_status
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public void setJobStatus(String jobStatus) {
        this.jobStatus = jobStatus == null ? null : jobStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_keda_caseinfo.job_time
     *
     * @return the value of t_keda_caseinfo.job_time
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public Date getJobTime() {
        return jobTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_keda_caseinfo.job_time
     *
     * @param jobTime the value for t_keda_caseinfo.job_time
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    public void setJobTime(Date jobTime) {
        this.jobTime = jobTime;
    }
}