package com.ai.mine.crystal.dao.model;

public class TUserExtension {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_extension.user_id
     *
     * @mbg.generated Tue Oct 30 16:23:58 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_extension.industry
     *
     * @mbg.generated Tue Oct 30 16:23:58 CST 2018
     */
    private String industry;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_extension.user_id
     *
     * @return the value of t_user_extension.user_id
     *
     * @mbg.generated Tue Oct 30 16:23:58 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_extension.user_id
     *
     * @param userId the value for t_user_extension.user_id
     *
     * @mbg.generated Tue Oct 30 16:23:58 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_extension.industry
     *
     * @return the value of t_user_extension.industry
     *
     * @mbg.generated Tue Oct 30 16:23:58 CST 2018
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_extension.industry
     *
     * @param industry the value for t_user_extension.industry
     *
     * @mbg.generated Tue Oct 30 16:23:58 CST 2018
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }
}