package com.ai.mine.crystal.dao.mapper;

import com.ai.mine.crystal.dao.model.TKedaVideoStorage;
import com.ai.mine.crystal.dao.model.TKedaVideoStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TKedaVideoStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keda_video_storage
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    long countByExample(TKedaVideoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keda_video_storage
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    int deleteByExample(TKedaVideoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keda_video_storage
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    int deleteByPrimaryKey(Long videoStorageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keda_video_storage
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    int insert(TKedaVideoStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keda_video_storage
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    int insertSelective(TKedaVideoStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keda_video_storage
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    List<TKedaVideoStorage> selectByExample(TKedaVideoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keda_video_storage
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    TKedaVideoStorage selectByPrimaryKey(Long videoStorageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keda_video_storage
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") TKedaVideoStorage record, @Param("example") TKedaVideoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keda_video_storage
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    int updateByExample(@Param("record") TKedaVideoStorage record, @Param("example") TKedaVideoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keda_video_storage
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    int updateByPrimaryKeySelective(TKedaVideoStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keda_video_storage
     *
     * @mbg.generated Thu Jun 13 15:34:29 CST 2019
     */
    int updateByPrimaryKey(TKedaVideoStorage record);
}