package com.ai.mine.crystal.dao.mapper;

import com.ai.mine.crystal.dao.model.TKedaCaseinfo;
import com.ai.mine.crystal.dao.model.TKedaCaseinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TKedaCaseinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keda_caseinfo
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    long countByExample(TKedaCaseinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keda_caseinfo
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    int deleteByExample(TKedaCaseinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keda_caseinfo
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    int deleteByPrimaryKey(String caseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keda_caseinfo
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    int insert(TKedaCaseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keda_caseinfo
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    int insertSelective(TKedaCaseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keda_caseinfo
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    List<TKedaCaseinfo> selectByExample(TKedaCaseinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keda_caseinfo
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    TKedaCaseinfo selectByPrimaryKey(String caseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keda_caseinfo
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") TKedaCaseinfo record, @Param("example") TKedaCaseinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keda_caseinfo
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    int updateByExample(@Param("record") TKedaCaseinfo record, @Param("example") TKedaCaseinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keda_caseinfo
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    int updateByPrimaryKeySelective(TKedaCaseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_keda_caseinfo
     *
     * @mbg.generated Thu Jun 13 14:37:16 CST 2019
     */
    int updateByPrimaryKey(TKedaCaseinfo record);
}