package com.ai.mine.crystal.dao.mapper;

import com.ai.mine.crystal.dao.model.TSysParameters;
import com.ai.mine.crystal.dao.model.TSysParametersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSysParametersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_parameters
     *
     * @mbg.generated Thu Jun 13 22:56:15 CST 2019
     */
    long countByExample(TSysParametersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_parameters
     *
     * @mbg.generated Thu Jun 13 22:56:15 CST 2019
     */
    int deleteByExample(TSysParametersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_parameters
     *
     * @mbg.generated Thu Jun 13 22:56:15 CST 2019
     */
    int deleteByPrimaryKey(String paramCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_parameters
     *
     * @mbg.generated Thu Jun 13 22:56:15 CST 2019
     */
    int insert(TSysParameters record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_parameters
     *
     * @mbg.generated Thu Jun 13 22:56:15 CST 2019
     */
    int insertSelective(TSysParameters record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_parameters
     *
     * @mbg.generated Thu Jun 13 22:56:15 CST 2019
     */
    List<TSysParameters> selectByExample(TSysParametersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_parameters
     *
     * @mbg.generated Thu Jun 13 22:56:15 CST 2019
     */
    TSysParameters selectByPrimaryKey(String paramCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_parameters
     *
     * @mbg.generated Thu Jun 13 22:56:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") TSysParameters record, @Param("example") TSysParametersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_parameters
     *
     * @mbg.generated Thu Jun 13 22:56:15 CST 2019
     */
    int updateByExample(@Param("record") TSysParameters record, @Param("example") TSysParametersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_parameters
     *
     * @mbg.generated Thu Jun 13 22:56:15 CST 2019
     */
    int updateByPrimaryKeySelective(TSysParameters record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_parameters
     *
     * @mbg.generated Thu Jun 13 22:56:15 CST 2019
     */
    int updateByPrimaryKey(TSysParameters record);
}